language: node_js
node_js: '6'
matrix:
  include:
    - os: linux
      env:
        - VERSION=0.3.1
        - OS=linux
    - os: linux
      env:
        - VERSION=0.4.1
        - OS=linux
    - os: linux
      env:
        - VERSION=0.16.0
        - OS=linux
    - os: linux
      env:
        - VERSION=0.24.0
        - OS=linux
    - os: linux
      env:
        - VERSION=0.25.0
        - OS=linux
    - os: osx
      osx_image: xcode9
      env:
        - VERSION=0.3.1
        - OS=darwin
    - os: osx
      osx_image: xcode9
      env:
        - VERSION=0.4.1
        - OS=darwin
    - os: osx
      osx_image: xcode9
      env:
        - VERSION=0.16.0
        - OS=darwin
    - os: osx
      osx_image: xcode9
      env:
        - VERSION=0.24.0
        - OS=darwin
    - os: osx
      osx_image: xcode9
      env:
        - VERSION=0.25.0
        - OS=darwin
script:
  - npm i
  - mkdir -p ./node_modules/.bin
  - curl -SL "https://github.com/fibjs/fibjs/releases/download/v${VERSION}/fibjs-v${VERSION}-${OS}-x64.xz" -o ./node_modules/.bin/fibjs.xz
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install xz;
    fi
  - xz -d ./node_modules/.bin/fibjs.xz
  - chmod a+x ./node_modules/.bin/fibjs
  - npm run ci
